namespace Fig.Web.Models.ClientHistory;

/// <summary>
/// Represents a client definition imported from a JSON file generated by the --setting-definitions argument.
/// </summary>
public class ImportedClientDefinition
{
    public string ClientName { get; set; } = string.Empty;
    
    public string ClientVersion { get; set; } = string.Empty;
    
    public DateTime GeneratedDateUtc { get; set; }
    
    public List<SettingDefaultValueModel> Settings { get; set; } = new();
}
