# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY src/ src/
COPY examples/Fig.Examples.AspNetApi/ examples/Fig.Examples.AspNetApi/
COPY examples/Fig.Examples.AspNetApi/ examples/Fig.Examples.AspNetApi/
COPY src/Fig.sln src/Fig.sln
RUN dotnet restore "src/Fig.sln"
RUN dotnet publish "examples/Fig.Examples.AspNetApi/Fig.Examples.AspNetApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Fig.Examples.AspNetApi.dll"]
