using System;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;

namespace Fig.Client.AppSettings;

internal class FigOfflineConfigurationProvider : Microsoft.Extensions.Configuration.ConfigurationProvider
{
    private readonly List<IConfigurationSource> _preFigSources;
    private readonly IDpapiValueProcessor _dpapiProcessor;

    public FigOfflineConfigurationProvider(List<IConfigurationSource> preFigSources)
        : this(preFigSources, new DpapiValueProcessor())
    {
    }

    internal FigOfflineConfigurationProvider(
        List<IConfigurationSource> preFigSources,
        IDpapiValueProcessor dpapiProcessor)
    {
        _preFigSources = preFigSources;
        _dpapiProcessor = dpapiProcessor;
    }

    public override void Load()
    {
        if (!_dpapiProcessor.IsSupported)
            return;

        var tempBuilder = new ConfigurationBuilder();
        foreach (var source in _preFigSources)
            tempBuilder.Add(source);

        IConfigurationRoot tempConfig;
        try
        {
            tempConfig = tempBuilder.Build();
        }
        catch (Exception)
        {
            // If building the temp config fails, skip decryption silently
            return;
        }

        foreach (var kvp in tempConfig.AsEnumerable())
        {
            if (kvp.Key == null || kvp.Value == null)
                continue;

            if (!kvp.Key.EndsWith(AppSettingsGenerator.EncryptedSuffix, StringComparison.OrdinalIgnoreCase))
                continue;

            var plainKey = kvp.Key.Substring(
                0, kvp.Key.Length - AppSettingsGenerator.EncryptedSuffix.Length);

            // Respect configuration precedence: if a plain-text value already exists
            // for this key (e.g. from an environment variable override), skip decryption.
            if (tempConfig[plainKey] != null)
                continue;

            try
            {
                Data[plainKey] = _dpapiProcessor.Decrypt(kvp.Value);
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(
                    $"[Fig] Warning: Failed to decrypt setting '{plainKey}' from '{kvp.Key}'. " +
                    $"Ensure the file was generated by the same Windows user running this application. " +
                    $"Details: {ex.Message}");
            }
        }
    }
}
