using System;
using System.Collections.Generic;
using Fig.Client.Contracts;
using Microsoft.Extensions.Configuration;

namespace Fig.Client.AppSettings;

internal class FigOfflineConfigurationProvider : Microsoft.Extensions.Configuration.ConfigurationProvider
{
    private readonly List<IConfigurationSource> _preFigSources;
    private readonly IAppSettingsEncryptionProvider? _encryptionProvider;

    internal FigOfflineConfigurationProvider(
        List<IConfigurationSource> preFigSources,
        IAppSettingsEncryptionProvider? encryptionProvider = null)
    {
        _preFigSources = preFigSources;
        _encryptionProvider = encryptionProvider;
    }

    public override void Load()
    {
        if (_encryptionProvider == null || !_encryptionProvider.IsSupported)
        {
            Console.Error.WriteLine(
                _encryptionProvider == null
                    ? "[Fig] Warning: --figoffline is active but no encryption provider is configured. " +
                      "Secret settings will not be decrypted. " +
                      "Add a DpapiSecretProvider (or another IClientSecretProvider that implements IAppSettingsEncryptionProvider) to FigOptions.ClientSecretProviders."
                    : "[Fig] Warning: --figoffline is active but the configured encryption provider is not supported on this platform. " +
                      "Secret settings will not be decrypted.");
            return;
        }

        var tempBuilder = new ConfigurationBuilder();
        foreach (var source in _preFigSources)
            tempBuilder.Add(source);

        IConfigurationRoot tempConfig;
        try
        {
            tempConfig = tempBuilder.Build();
        }
        catch (Exception)
        {
            Console.Error.WriteLine(
                "[Fig] Warning: --figoffline is active but the configuration sources could not be built. " +
                "Secret settings will not be decrypted.");
            return;
        }

        foreach (var kvp in tempConfig.AsEnumerable())
        {
            if (kvp.Key == null || kvp.Value == null)
                continue;

            if (!kvp.Key.EndsWith(AppSettingsGenerator.EncryptedSuffix, StringComparison.OrdinalIgnoreCase))
                continue;

            var plainKey = kvp.Key.Substring(
                0, kvp.Key.Length - AppSettingsGenerator.EncryptedSuffix.Length);

            // Respect configuration precedence: if a plain-text value already exists
            // for this key (e.g. from an environment variable override), skip decryption.
            if (tempConfig[plainKey] != null)
                continue;

            try
            {
                Data[plainKey] = _encryptionProvider.Decrypt(kvp.Value);
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(
                    $"[Fig] Warning: Failed to decrypt setting '{plainKey}' from '{kvp.Key}'. " +
                    $"Ensure the file was generated by the same Windows user running this application. " +
                    $"Details: {ex.Message}");
            }
        }
    }
}
