name: Create Release

on:
  push:
    tags:
      - "v*"
      - "!*-alpha"

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  release:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Update .NET workloads
      run: dotnet workload update
    
    - name: Install required .NET workloads
      run: dotnet workload install aspire

    - name: Install dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet build --configuration Release --no-restore ./src

    - name: Test
      run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" ./src 

    - name: Publish Api
      run: dotnet publish ./src/api/Fig.Api/Fig.Api.csproj --runtime win-x64 --configuration Release --self-contained true -p:PublishSingleFile=true -p:PublishedTrimmed=true -p:IncludeAllContentForSelfExtract=true

    - name: Zip API
      uses: papeloto/action-zip@v1
      with:
        files: ./src/api/Fig.Api/bin/Release/net9.0/win-x64/publish
        dest: ./src/api/Fig.Api/bin/Release/net9.0/win-x64/Fig.Api.zip

    - name: Publish Web
      run: dotnet publish ./src/web/Fig.Web/Fig.Web.csproj --runtime win-x64 --configuration Release --self-contained true -p:PublishedTrimmed=true -p:IncludeAllContentForSelfExtract=true

    - name: Zip Web
      uses: papeloto/action-zip@v1
      with:
        files: ./src/web/Fig.Web/bin/Release/net9.0/publish
        dest: ./src/web/Fig.Web/bin/Release/net9.0/Fig.Web.zip

    - name: Publish Encryption Tool
      run: dotnet publish ./src/tools/Fig.Dpapi.Client/Fig.Dpapi.Client.csproj --configuration Release
  
    - name: Zip Encryption Tool
      uses: papeloto/action-zip@v1
      with:
        files: ./src/tools/Fig.Dpapi.Client/bin/Release/net9.0-windows/win-x64/publish/
        dest: ./src/tools/Fig.Dpapi.Client/bin/Release/net9.0-windows/win-x64/Fig.Dpapi.Client.zip

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        gh release create ${{ github.ref_name }} --generate-notes ./src/api/Fig.Api/bin/Release/net9.0/win-x64/Fig.Api.zip ./src/web/Fig.Web/bin/Release/net9.0/Fig.Web.zip ./src/tools/Fig.Dpapi.Client/bin/Release/net9.0-windows/win-x64/Fig.Dpapi.Client.zip