name: End To End

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      # Prevent running in parallel
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: 8.0.x
        
    - name: Install dotnet-serve
      run: dotnet tool install --global dotnet-serve

    - name: Install required workloads
      run: dotnet workload install aspire

    - name: Restore dependencies
      run: dotnet restore ./src/Fig.sln

    - name: Build Test
      run: dotnet build ./src/tests/Fig.EndToEnd.Tests/Fig.EndToEnd.Tests.csproj --no-restore

    - name: Install Playwright dependencies
      # Only needed on Linux
      if: ${{ runner.os == 'Linux' }}
      run: pwsh ./src/tests/Fig.EndToEnd.Tests/bin/Debug/net8.0/playwright.ps1 install-deps

    - name: Install Playwright
      run: pwsh ./src/tests/Fig.EndToEnd.Tests/bin/Debug/net8.0/playwright.ps1 install

    - name: Start application
      shell: bash
      run: |
        dotnet run --project ./src/hosting/Fig.AppHost/Fig.AppHost.csproj &
        npx wait-on https://localhost:7148

    - name: Playwright test Webkit
      # Web assembly is not fully supported on Windows and Webkit (https://github.com/microsoft/playwright/issues/2876)
      if: ${{ runner.os != 'Windows' }}
      run: dotnet test ./src/tests/Fig.EndToEnd.Tests/Fig.EndToEnd.Tests.csproj --no-restore -- Playwright.BrowserName=webkit
        
    - name: Playwright test Firefox
      run: dotnet test ./src/tests/Fig.EndToEnd.Tests/Fig.EndToEnd.Tests.csproj --no-restore -- Playwright.BrowserName=firefox

    - name: Playwright test Chromium
      run: dotnet test ./src/tests/Fig.EndToEnd.Tests/Fig.EndToEnd.Tests.csproj --no-restore -- Playwright.BrowserName=chromium

    - name: Upload Playwright logs
      if: failure()
      uses: actions/upload-artifact@v4.3.2
      with:
        name: playwright
        retention-days: 2
        path: |
          ./src/tests/Fig.EndToEnd.Tests/bin/Debug/net8.0/playwright-traces/**/*.*